SAK-44299 Rubrics and other modules are broken in master
adrianfish/empathise pull request #3
Opened 2020-09-15 15:42 UTC by MRutea

I've found a problem with the file inject-process-module.js from the external library empathise; "/empathise": "^0.1.8".
SAK-44299 Rubrics and other modules are broken in master
related to jira issue SAK-4429.

2020-09-17 08:36 UTC, mpellicer requested changes

2020-09-17 08:36 UTC, mpellicer commented on src/transform/inject-process-module.js
> +        var relativePath = path_1.relative(path_1.dirname(file.path), processModuleFile.path);
Spacing and use LET instead of VAR.

2020-09-17 13:54 UTC, adrianfish approved these changes
GTG

2020-09-17 13:54 UTC, merged

2020-09-17 13:56 UTC, adrianfish commented
This will need a new version of the npm artefact.

2020-09-23 12:17 UTC, SedueRey commented
Hello, @adrianfish ... this has broken rubricks in our 20.0 servers in production. In 20. Unbelievable.

2020-09-23 13:23 UTC, mpellicer commented
@SedueRey I'm curious, how this change broke rubrics in 20.x? This change has been merged to Main (Master) and the 0.1.9 tag is not released yet, the change is not merged in Sakai Main (Master) yet.....

2020-09-29 12:16 UTC, SedueRey commented
@mpellicer sorry, my mistake. I said that was unbelievable and finally was a different thing, we shouldn't have applied a patch in our servers.
And sorry in the delay answering this messages too. A rough course start.